version: "3"

services:
  api:
    restart: always
    build: ./backEnd
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "db-test"
    volumes:
      - ./backEnd:/usr/src/api
      - /usr/src/api/node_modules
      - /usr/src/api/coverage
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
  db-test:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5430:5432"
