version: "3"

services:
  api:
    restart: always
    build: ./backEnd
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ./backEnd:/usr/src/api
      - /usr/src/api/node_modules
    env_file:
      - .env
  mongo:
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
